Handles jumpboxes with more than one IP address
genesis-community/jumpbox-genesis-kit pull request #15
Opened 2018-06-12 04:13 UTC by dennisjbell

Properly handles jumpboxes with more than one IP, defaulting to the internal IP for ssh and who addon.

2018-06-13 01:45 UTC, dennisjbell commented
Don't merge -- this needs further changes to better support selecting the correct IP address.

2018-06-13 13:12 UTC, jhunt commented
Was this done prior to the discussion we had yesterday about the hacky workaround in place that got you to a dual-homed jumpbox in the first place?

2018-08-07 20:23 UTC, jhunt commented
@patrick1378 I think this is reviewable now; @dennisjbell can weigh in.  I added some changes to make the bastion networks a real thing...

2018-08-08 13:58 UTC, patjones requested changes
running any `genesis do ...` will result in 

`./hooks/addon: line 5: syntax error near unexpected token `=$(bosh vms --json | jq -r '.Tables[0].Rows[0].ips')'
Could not run 'addon' hook successfully`

2018-08-08 13:58 UTC, patrick1378 commented on hooks/addon
> +ips( =$(bosh vms --json | jq -r '.Tables[0].Rows[0].ips') )
Switching to `ips=( $(bosh vms --json | jq -r '.Tables[0].Rows[0].ips') )` will fix addon

2018-08-08 16:47 UTC, patjones approved these changes

2018-08-08 19:02 UTC, merged